package pl.edu.agh.utils;

public enum Instrument {
    PIANO, HARPSICHORD, XYLOPHONE, ORGAN, CHURCH_ORGAN, ACCORDION, HARMONICA,
    GUITAR, ELECTRIC_GUITAR, BASS, VIOLIN, VIOLA, CELLO, CONTRABASS, HARP,
    TRUMPET, TROMBONE, TUBA, SAXOPHONE, OBOE, ENGLISH_HORN, BASSOON,
    CLARINET, FLUTE, DRUMS;
}
